### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed

### ISSUE THREAD

**Issue by sidjakinsboriss** [mgorabbani/react-image-pan-zoom-rotate#44]
Hi, I´m getting the following warning when using the package:

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ReactPanZoom

**Comment by mgorabbani** [comment]
Fixed!

**Comment by JodieW89** [comment]
@mgorabbani Technically it's working, but still getting this warning when in strict mode:
<img width="606" alt="Screenshot 2022-12-13 at 16 33 18" src="https://user-images.githubusercontent.com/47717542/207390504-9aab89ad-e571-4571-b275-e0576681c28f.png">

Any plans to implement a refactor for this in the future?

**Comment by Stefano191** [comment]
I would like to re-open this issue, because it isnt fixed.
